# Generated by Django 2.2.7 on 2020-01-27 21:40

import django.db.models.deletion
from django.db import migrations, models

import legacy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegacyAccessattempt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_agent", models.CharField(max_length=255)),
                ("ip_address", models.CharField(blank=True, max_length=39, null=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("trusted", models.IntegerField()),
                ("http_accept", models.CharField(max_length=1025)),
                ("path_info", models.CharField(max_length=255)),
                ("attempt_time", models.DateTimeField()),
                ("get_data", models.TextField()),
                ("post_data", models.TextField()),
                ("failures_since_start", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LegacyAccesslog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_agent", models.CharField(max_length=255)),
                ("ip_address", models.CharField(blank=True, max_length=39, null=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("trusted", models.IntegerField()),
                ("http_accept", models.CharField(max_length=1025)),
                ("path_info", models.CharField(max_length=255)),
                ("attempt_time", models.DateTimeField()),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LegacyCustomer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_order", models.IntegerField()),
                ("join_date", models.DateField()),
                ("active", models.IntegerField()),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=50)),
                ("printed_notes", models.TextField()),
                ("place_of_worship", models.CharField(max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("sex", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=200)),
                ("contact_phone", models.CharField(max_length=50)),
                ("doctor", models.CharField(max_length=200)),
                ("hospital", models.CharField(max_length=200)),
                ("cold_diet_restrictions", models.CharField(max_length=200)),
                ("hot_diet_restrictions", models.CharField(max_length=200)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("referred", models.CharField(max_length=200)),
                ("ref_phone", models.CharField(max_length=50)),
                ("agency", models.CharField(max_length=200)),
                ("in_care_of", models.CharField(max_length=200)),
                ("bill_to", models.CharField(max_length=200)),
                ("notes", models.TextField()),
                ("recurrences", models.TextField(blank=True, null=True)),
                ("num_weekend_meals", models.IntegerField()),
                ("location", models.CharField(blank=True, max_length=42, null=True)),
                ("death_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LegacyDiet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=5)),
            ],
            bases=(legacy.models.EasyImportMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LegacyDjangoContentType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LegacyDjangoMigrations",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="LegacyDjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="LegacyDjangoSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="LegacyDontsendentry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_address", models.CharField(max_length=254)),
                ("when_added", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="LegacyGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LegacyMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_data", models.TextField()),
                ("when_added", models.DateTimeField()),
                ("priority", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="LegacyMessagelog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_data", models.TextField()),
                ("when_added", models.DateTimeField()),
                ("priority", models.CharField(max_length=1)),
                ("when_attempted", models.DateTimeField()),
                ("result", models.CharField(max_length=1)),
                ("log_message", models.TextField()),
                ("message_id", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LegacyPackerjob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LegacyPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            bases=(legacy.models.EasyImportMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LegacyPet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            bases=(legacy.models.EasyImportMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LegacyPetFood",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=5)),
            ],
            bases=(legacy.models.EasyImportMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LegacyRoute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route", models.IntegerField()),
                (
                    "calendarId",
                    models.CharField(db_column="calendarId", max_length=200),
                ),
                ("description", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="LegacyShuttleroute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LegacyUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
            ],
            bases=(legacy.models.EasyImportMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LegacyUserinfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calendarid",
                    models.CharField(db_column="calendarId", max_length=200),
                ),
                ("username", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="LegacyVolunteer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("organization", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip", models.CharField(max_length=100)),
                ("home_phone", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100)),
                ("cell_phone", models.CharField(max_length=50)),
                ("work_phone", models.CharField(max_length=50)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField()),
                ("join_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyUser",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyVolunteershuttleroute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recurrences", models.TextField()),
                (
                    "shuttle_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyShuttleroute",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyVolunteer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyVolunteerroute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recurrences", models.TextField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyRoute",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyVolunteer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyVolunteerpackerjob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recurrences", models.TextField()),
                (
                    "packer_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyPackerjob",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyVolunteer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyUserGroups",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyGroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyUser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacySubstitutionrequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyUser",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyRoute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacySubstitution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "requested_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyUser",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyRoute",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyVolunteer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyShuttleroutesubstitutionrequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyUser",
                    ),
                ),
                (
                    "shuttle_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyShuttleroute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyShuttleroutesubstitution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "requested_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyUser",
                    ),
                ),
                (
                    "shuttle_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyShuttleroute",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyVolunteer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyReportday",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("num_meals", models.IntegerField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyCustomer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyDjangoContentType",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyPackerjobsubstitutionrequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyUser",
                    ),
                ),
                (
                    "packer_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyPackerjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyPackerjobsubstitution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "packer_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyPackerjob",
                    ),
                ),
                (
                    "requested_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyUser",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyVolunteer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyManagerannouncement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_until", models.DateField()),
                ("date_created", models.DateField()),
                ("announcement", models.TextField()),
                ("display", models.IntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyUser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyGroupPermissions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyGroup",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyPermission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyDjangoAdminLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.SmallIntegerField()),
                ("change_message", models.TextField()),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyDjangoContentType",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyUser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyDateRange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="legacy.LegacyCustomer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="legacycustomer",
            name="diet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="legacy.LegacyDiet",
            ),
        ),
        migrations.AddField(
            model_name="legacycustomer",
            name="pays",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="legacy.LegacyPayment",
            ),
        ),
        migrations.AddField(
            model_name="legacycustomer",
            name="pet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="legacy.LegacyPet",
            ),
        ),
        migrations.AddField(
            model_name="legacycustomer",
            name="petfood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="legacy.LegacyPetFood",
            ),
        ),
        migrations.AddField(
            model_name="legacycustomer",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="legacy.LegacyRoute",
            ),
        ),
    ]
