# Generated by Django 2.2.7 on 2020-01-27 21:40

import datetime

import address.models
import django.db.models.deletion
import recurrence.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("address", "0002_auto_20160213_1726"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_order", models.IntegerField(default=0)),
                ("join_date", models.DateField(default=datetime.date.today)),
                ("active", models.BooleanField(default=False)),
                (
                    "first_name",
                    models.CharField(db_index=True, default="", max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(db_index=True, default="", max_length=100),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("printed_notes", models.TextField(blank=True, default="")),
                ("birth_date", models.DateField(null=True)),
                ("sex", models.CharField(blank=True, default="", max_length=50)),
                ("contact", models.CharField(blank=True, default="", max_length=200)),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "cold_diet_restrictions",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "hot_diet_restrictions",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                ("end_reason", models.CharField(blank=True, max_length=200, null=True)),
                ("referred", models.CharField(blank=True, default="", max_length=200)),
                ("ref_phone", models.CharField(blank=True, default="", max_length=50)),
                ("bill_to", models.CharField(blank=True, default="", max_length=200)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "meal_recurrence",
                    recurrence.fields.RecurrenceField(
                        blank=True, default="", null=True
                    ),
                ),
                ("num_weekend_meals", models.PositiveIntegerField(default=0)),
                (
                    "address",
                    address.models.AddressField(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="address.Address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("code", models.CharField(default="", max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("num_vols_required", models.SmallIntegerField(default=1)),
                (
                    "recurrence",
                    recurrence.fields.RecurrenceField(
                        default="DTSTART:19700101T050000Z\nRRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PetFood",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("code", models.CharField(default="", max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="models.Job",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("number", models.IntegerField(unique=True)),
            ],
            bases=("models.job",),
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("home_phone", models.CharField(blank=True, default="", max_length=20)),
                ("cell_phone", models.CharField(blank=True, default="", max_length=20)),
                ("work_phone", models.CharField(blank=True, default="", max_length=20)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("join_date", models.DateField(default=datetime.date.today)),
                ("number_of_people", models.IntegerField(default=1)),
                (
                    "address",
                    address.models.AddressField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="address.Address",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManagerAnnouncement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_until", models.DateField(null=True)),
                ("date_created", models.DateField(auto_now=True)),
                ("announcement", models.TextField(default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="models.Volunteer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="models.JobType"
            ),
        ),
        migrations.CreateModel(
            name="DateRange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("end_date", models.DateField(default=datetime.date.today)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.Customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="diet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="models.Diet",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="pays",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="models.Payment",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="pet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="models.Pet",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="petfood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="models.PetFood",
            ),
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                (
                    "week_of_month",
                    models.SmallIntegerField(
                        choices=[
                            (1, "first"),
                            (2, "second"),
                            (3, "third"),
                            (4, "fourth"),
                            (5, "fifth"),
                        ]
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="models.Job"
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="models.Volunteer",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("job", "volunteer", "day_of_week", "week_of_month")
                },
            },
        ),
        migrations.CreateModel(
            name="Substitution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.Assignment",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteer",
                        to="models.Volunteer",
                    ),
                ),
            ],
            options={"unique_together": {("volunteer", "assignment", "date")}, },
        ),
        migrations.AddField(
            model_name="customer",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="models.Route",
            ),
        ),
        migrations.CreateModel(
            name="CustomerRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("num_meals", models.IntegerField()),
                (
                    "customer",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="models.Customer",
                    ),
                ),
                (
                    "payment_type",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="models.Payment",
                    ),
                ),
                (
                    "route_assigned",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="models.Route",
                    ),
                ),
            ],
            options={"unique_together": {("customer", "date")}, },
        ),
        migrations.AlterOrderWithRespectTo(
            name="customer", order_with_respect_to="route",
        ),
    ]
