# Generated by Django 2.2.7 on 2020-01-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="dont_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("first_name", "last_name", "contact", "contact_phone")},
        ),
    ]
