# Generated by Django 2.2.7 on 2020-01-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0002_auto_20200128_1619"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="cell_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="home_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="work_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
