# Generated by Django 2.2.7 on 2020-02-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0003_auto_20200128_1636"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="route_order",),
    ]
