# Generated by Django 2.2.7 on 2020-02-06 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_remove_customer_route_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerannouncement',
            name='date_created',
            field=models.DateField(
                default=datetime.date.today,
                editable=False),
        ),
    ]
