# Generated by Django 2.2.7 on 2020-02-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0004_remove_customer_route_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="historical_route",
            field=models.CharField(default="", max_length=100),
        ),
    ]
