# Generated by Django 2.2.7 on 2020-02-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20200206_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='dont_email',
            field=models.BooleanField(default=False),
        ),
    ]
