# Generated by Django 2.2.7 on 2020-02-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0006_auto_20200207_2047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="historical_route",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
