# Generated by Django 2.2.7 on 2020-02-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_volunteer_dont_email'),
        ('models', '0007_auto_20200209_1730'),
    ]

    operations = [
    ]
