# Generated by Django 2.2.7 on 2020-02-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_merge_20200212_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment', name='week_of_month', field=models.SmallIntegerField(
                choices=[
                    (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')]), ), ]
