# Generated by Django 2.2.7 on 2020-02-28 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20200226_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRecord',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('date',
                 models.DateField(
                     default=datetime.date.today)),
                ('job',
                 models.ForeignKey(
                     default=None,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='models.Job')),
                ('volunteer',
                 models.ForeignKey(
                     default=None,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     to='models.Volunteer')),
            ],
        ),
    ]
