# Generated by Django 2.2.7 on 2020-02-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20200225_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lae',
            new_name='lat',
        ),
    ]
