# Generated by Django 2.2.7 on 2020-02-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20200225_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lon',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
