# Generated by Django 2.2.7 on 2020-03-01 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20200301_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrecord',
            name='original',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='models.Volunteer'),
        ),
        migrations.AlterField(
            model_name='volunteerrecord',
            name='volunteer',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='record',
                to='models.Volunteer'),
        ),
    ]
