# Generated by Django 2.2.7 on 2020-03-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_auto_20200301_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrecord',
            name='is_substitution',
        ),
    ]
