# Generated by Django 2.2.7 on 2020-03-04 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_remove_volunteerrecord_is_substitution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='volunteer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='models.Volunteer'),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='volunteer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='volunteer',
                to='models.Volunteer'),
        ),
    ]
