# Generated by Django 2.2.7 on 2020-03-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_volunteerrecord_is_substitution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['job_type']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
    ]
