# Generated by Django 2.2.7 on 2020-03-17 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_auto_20200305_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['route__number', 'job_type']},
        ),
    ]
