# Generated by Django 2.2.7 on 2020-03-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20200226_1000'),
        ('models', '0017_auto_20200305_1620'),
    ]

    operations = [
    ]
