# Generated by Django 2.2.7 on 2020-03-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_merge_20200315_1707'),
        ('models', '0019_auto_20200316_2302'),
    ]

    operations = [
    ]
