# Generated by Django 2.2.7 on 2020-03-30 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_merge_20200317_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='diet',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='models.Diet'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pays',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='models.Payment'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pet',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='models.Pet'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='petfood',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='models.PetFood'),
        ),
    ]
