# Generated by Django 3.0.4 on 2020-04-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_auto_20200329_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtype',
            options={'ordering': ['name']},
        ),
    ]
