# Generated by Django 4.0.3 on 2022-04-17 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_auto_20200411_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(max_length=50)),
                ('customer_status', models.CharField(max_length=50, null=True)),
                ('notes', models.CharField(max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.customer')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.route')),
            ],
        ),
    ]
