# Generated by Django 4.0.3 on 2022-04-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0023_deliveryfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryfeedback',
            name='route',
        ),
    ]
