# Generated by Django 4.0.3 on 2022-04-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_remove_deliveryfeedback_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(auto_now_add=True)),
                ('delivery_status', models.CharField(max_length=50)),
                ('customer_status', models.CharField(max_length=50, null=True)),
                ('notes', models.CharField(max_length=250, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.customer')),
            ],
        ),
    ]
