# Generated by Django 4.0.3 on 2022-04-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_run'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(fields=('customer', 'run_date'), name='customer_rundate'),
        ),
    ]
