# Generated by Django 4.0.3 on 2022-04-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_run_customer_rundate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='delivery_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
