# Generated by Django 4.0.3 on 2022-04-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0027_alter_run_delivery_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryFeedback',
        ),
    ]
