# Generated by Django 4.0.3 on 2022-04-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0028_delete_deliveryfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_date',
            field=models.DateField(),
        ),
    ]
