# Generated by Django 4.0.3 on 2022-04-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0029_alter_run_run_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='models.route'),
        ),
    ]
