# Generated by Django 4.0.4 on 2022-06-21 18:57

from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0030_alter_customer_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='receivesBonusPantryDelivery',
            field=models.BooleanField(default=True, verbose_name='Receives Bonus Pantry Delivery'),
        ),
        migrations.AddField(
            model_name='route',
            name='bonusRoute',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.route'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='day_of_week',
            field=models.SmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='week_of_month',
            field=models.SmallIntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='recurrence',
            field=recurrence.fields.RecurrenceField(),
        ),
    ]
