# Generated by Django 4.0.4 on 2023-02-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0031_customer_receivesbonuspantrydelivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='family_friendly_route',
            field=models.BooleanField(default=True),
        ),
    ]
