# Generated by Django 4.0.4 on 2023-05-01 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0032_route_family_friendly_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='bonusRoute',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.route'),
        ),
    ]
